"""tokens update

Revision ID: 5f47c56222e7
Revises: 1996f401d520
Create Date: 2023-03-10 17:33:12.841764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f47c56222e7'
down_revision = '1996f401d520'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('id_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'id_token')
    # ### end Alembic commands ###
