"""tokens: expires_in was DateTime, now Interval

Revision ID: 6dfc0698add1
Revises: 473a097c89de
Create Date: 2022-10-18 08:39:56.969728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfc0698add1'
down_revision = '473a097c89de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'expires_in', nullable=True, type=sa.Interval())
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'expires_in', nullable=True, type=sa.DateTime())    
    pass
    # ### end Alembic commands ###
