"""states: created, is_active

Revision ID: a67a8c651a72
Revises: fc908a9046d4
Create Date: 2022-09-12 18:59:34.207959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67a8c651a72'
down_revision = 'fc908a9046d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('states', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'is_active')
    op.drop_column('states', 'created')
    # ### end Alembic commands ###
